### ISSUE TITLE
Missing src files

### ISSUE THREAD

**Issue by danielchalef** [tzutalin/ros_caffe#1]
Does look like you've `push`ed all source. For one, `Makefile` is missing. Am assuming other files too.

**Comment by tzutalin** [comment]
Hi,
Sorry. The build path is wrong in README. I fixed the readme now. 
You should build submodule, Caffe, in $CATKIN_WS/src/ros_caffe/caffe.
`cd $CATKIN_WS/src/ros_caffe/caffe` instead of `cd $CATKIN_WS/src/ros_caffe` 

Changes:
https://github.com/tzutalin/ros_caffe/commit/a57722193a9ef231ac56c0fb275f79bc7efdbe0c

**Comment by danielchalef** [comment]
Thanks. I've already got caffe installed. I assume I can link to it by modifying the Makefile?

**Comment by tzutalin** [comment]
Hi @danielchalef ,
  If you got Caffe installed before. You can specify your Caffe include and library path in CMakeLists as bellows.

https://github.com/tzutalin/ros_caffe/blob/master/CMakeLists.txt#L12

Change it like:
set(CAFFE_INCLUDEDIR caffe/include caffe/distribute/include) -> 
set(CAFFE_INCLUDEDIR /home/danielchalef/caffe/include /home/danielchalef/caffe/distribute/include)

**Comment by danielchalef** [comment]
Thanks. Compiling and testing worked. Outside of running `ros_caffe_test` what other node scripts are available?  Is there is a list of published ROS topics / messages / services?

**Comment by tzutalin** [comment]
I didn't published ROS topic yet in the sample code. But I can add a looper, topic, and sensor message to receive an image as input.  What kind of topics and messages do you like to publish after classification?

**Comment by danielchalef** [comment]
That would be great. How about class names and their probabilities ?

**Comment by tzutalin** [comment]
Ok. I will implement it

**Comment by danielchalef** [comment]
That would be great. Thanks!

**Comment by tzutalin** [comment]
Fix missing src files
