### ISSUE TITLE
Questions regarding using GPU

### ISSUE THREAD

**Issue by Astrosun** [tzutalin/ros_caffe#3]
Hi,

I have complied and run the roscaffe successfully. Thanks for your talent work and here I would like to ask some questions.

Is the default mode of this ros_caffe using GPU or CPU?( I chose GPU-caffe during building( did NOT uncomment CPU_ONLY := 1 in Makefile.config)
I ask this question because after I read the codes in "Classifier.h", I find that all the functions uses"cpu" version instead of "gpu" version, for example, in line 126, "float* data = mean_blob.mutable_cpu_data();" instead of "float* data = mean_blob.mutable_gpu_data();", Does this mean that when I am running the ros_caffe, I am using cpu instead of gpu even though I chose gpu during building?

I attempted to change all the functions related to cpu to gpu, I can successfully complied the file but when I ran it, it showed "segmentation fault".

Could you please help with this?

Thanks a lot!

**Comment by tzutalin** [comment]
Hi @Astrosun ,
  You build caffe and enable GPU. You should also remove add_definitions(-DCPU_ONLY=1) from my cmake file. 
  https://github.com/tzutalin/ros_caffe/blob/master/CMakeLists.txt#L4

**Comment by Astrosun** [comment]
Hi @tzutalin,

Thanks a lot for your reply.
After I removed add_definitions(-DCPU_ONLY=1) from the cmake file. I recompiled the package and it shows errors as indicated below.

/home/user/caffe/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
                       ^
compilation terminated.
make[2]: Leaving directory `/home/user/user_ws/build'
make[2]: *** [ros_caffe/CMakeFiles/ros_caffe_test.dir/src/ros_caffe_test.cpp.o] Error 1
make[1]: Leaving directory `/home/user/user_ws/build'
make[1]: *** [ros_caffe/CMakeFiles/ros_caffe_test.dir/all] Error 2
make: *** [all] Error 2

It seems like a caffe error to me first but then I change the caffe link in the cmake file to my own built already caffe, it still shows the same error.

Could you please explain more about this?

Thanks!

**Comment by Astrosun** [comment]
Problems solved by remaking everything from the beginning after removing add_definitions(-DCPU_ONLY=1)
