### ISSUE TITLE
segfault doing cv::Merge

### ISSUE THREAD

**Issue by lucbettaieb** [tzutalin/ros_caffe#6]
Hi,
In your SetMean method inside Classifier.h it seems that the cv::Merge is causing a segfault.

Any ideas as to whats going on?
Luc

**Comment by aubo-ros** [comment]
I also meet the issue. How to solve this problem. Thinks.

**Comment by lucbettaieb** [comment]
I don't remember what I did, but I believe it may have been an issue with the version of OpenCV I was using...
